name: Deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Set up Node
        uses: actions/setup-node@main
        with:
          node-version: '12'
          check-latest: true
      - name: Create protected directory
        run: mkdir protected
      - name: Copy Firebase admin key
        run: echo '${{ secrets.FIREBASE_ADMIN_KEY }}' > protected/firebase-admin.json
      - name: Copy environment variables
        uses: w9jds/firebase-action@master
        with:
          args: functions:config:get > protected/env.json
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Install dependencies for public/main
        run: |
          cd public/main
          npm ci
          cd ../..
      - name: Install dependencies for public/blog
        run: |
          cd public/blog
          npm ci
          cd ../..
      - name: Install dependencies for functions
        run: |
          cd functions
          npm ci
          cd ..
      - name: Install dependencies for scripts
        run: |
          cd scripts
          npm ci
          cd ..
      - name: Install dependencies for emails
        run: |
          cd emails
          npm ci
          cd ..
      - name: Generate sitemap
        run: npm run generate-sitemap
      - name: Load preview deck
        run: npm run load-preview-deck
      - name: Build public/main
        run: npm run build -C public/main
      - name: Build public/blog
        run: npm run build -C public/blog
      - name: Save public assets
        run: npm run save-public-assets
      - name: Move public HTML file
        run: mv public/main/build/index.html functions/public.html
      - name: Build functions
        run: npm run build -C functions
      - name: Upload emails
        run: npm run upload-emails
      - name: Deploy
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
