name: Test
on:
  push:
    branches:
      - staging

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Set up Node
        uses: actions/setup-node@main
        with:
          node-version: '12'
          check-latest: true
      - name: Install dependencies for public/main
        run: |
          cd public/main
          npm ci
          cd ../..
      - name: Install dependencies for public/blog
        run: |
          cd public/blog
          npm ci
          cd ../..
      - name: Install dependencies for functions
        run: |
          cd functions
          npm ci
          cd ..
      - name: Install dependencies for emails
        run: |
          cd emails
          npm ci
          cd ..
      - name: Install dependencies for npm
        run: |
          cd npm
          npm ci
          cd ..
      - name: Build public/main
        run: npm run build -C public/main
      - name: Build public/blog
        run: npm run build -C public/blog
      - name: Build functions
        run: npm run build -C functions
      - name: Build npm
        run: npm run build -C npm
      - name: Test functions
        run: npm test -C functions
      - name: Test npm
        run: npm test -C npm
